package io.alw.css.cashflowconsumer.model.constants;

public interface CashflowConsumerExceptionSubCategoryType {
    String INVALID_MESSAGE = "INVALID_MESSAGE";
    String INVALID_FO_VERSION = "INVALID_FO_VERSION";
    String NOT_FIRST_VERSION = "NOT_FIRST_VERSION";
    String TRADEID_MISMATCH = "TRADEID_MISMATCH";
    String INCORRECT_CF_REVISION_TYPE = "INCORRECT_CF_REVISION_TYPE";
    String MISSING_SSI = "INACTIVE_OR_MISSING_SSI";
    String INACTIVE_COUNTERPARTY = "INACTIVE_COUNTERPARTY_CODE";
    String UNEXPECTED_REFDATA = "UNEXPECTED_REFDATA";
    String MISSING_NOSTRO = "INACTIVE_OR_MISSING_NOSTRO";
    String INACTIVE_ENTITY = "INACTIVE_ENTITY";
    String INACTIVE_CURRENCY = "INACTIVE_CURRENCY";
}
